AWSTemplateFormatVersion: "2010-09-09"
Description: Security group for ALB

Parameters:
  VPCId:
    Type: String
  MyIP:
    Type: String
  PrivateNetworkIp:
    Type: String

Resources:
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPCId
      GroupDescription: Allow HTTP and SSH traffic to the ALB
      Tags:
        - Key: Name
          Value: ALBSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: !Ref MyIP
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref PrivateNetworkIp
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0

Outputs:
  ALBSecurityGroupId:
    Value: !Ref ALBSecurityGroup
