AWSTemplateFormatVersion: "2010-09-09"
Description: Auto Scaling Group

Parameters:
  PrivateSubnetId:
    Type: String

  EC2SecurityGroupId:
    Type: String

  TargetGroupArn:
    Type: String

  InstanceType:
    Type: String

  KeyName:
    Type: String

Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: web-template
      LaunchTemplateData:
        InstanceType: !Ref InstanceType
        ImageId: ami-0427090fd1714168b
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !Ref EC2SecurityGroupId
        UserData:
          Fn::Base64: |
            #!/bin/bash
            yum update -y
            yum install -y httpd
            echo "<h1>Hello world from $(hostname -f)</h1>" > /var/www/html/index.html
            sed -i 's/^Listen 80/Listen 8080/' /etc/httpd/conf/httpd.conf
            sed -i 's/^<VirtualHost _default_:80>/<VirtualHost _default_:8080>/' /etc/httpd/conf/httpd.conf
            systemctl start httpd
            systemctl enable httpd

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref PrivateSubnetId
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: 1
      MaxSize: 3
      DesiredCapacity: 2
      TargetGroupARNs:
        - !Ref TargetGroupArn
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300

Outputs:
  AutoScalingGroupName:
    Description: The name of the Auto Scaling group
    Value: !Ref AutoScalingGroup
