AWSTemplateFormatVersion: "2010-09-09"
Description: Auto Scaling Group

Parameters:
  PrivateSubnetId:
    Type: String
    Description: The ID of the private subnet

  EC2SecurityGroupId:
    Type: String
    Description: The ID of the security group for the EC2 instances

  TargetGroupArn:
    Type: String
    Description: The ARN of the target group

  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type

  KeyName:
    Type: String
    Description: Name of the EC2 Key Pair

Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: web-template
      LaunchTemplateData:
        InstanceType: !Ref InstanceType
        ImageId: ami-0a0e5d9c7acc336f1
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !Ref EC2SecurityGroupId
        UserData: !Base64 |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          echo "<h1>Hello world from $(hostname -f)</h1>" > /var/www/html/index.html
          sed -i 's/^Listen 80/Listen 8080/' /etc/httpd/conf/httpd.conf
          sed -i 's/^<VirtualHost _default_:80>/<VirtualHost _default_:8080>/' /etc/httpd/conf/httpd.conf
          systemctl start httpd
          systemctl enable httpd

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref PrivateSubnetId
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: 1
      MaxSize: 3
      DesiredCapacity: 2
      TargetGroupARNs:
        - !Ref TargetGroupArn
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300

Outputs:
  AutoScalingGroupName:
    Description: The name of the Auto Scaling group
    Value: !Ref AutoScalingGroup
