AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 Security Group Stack

Parameters:
  VPCId:
    Type: String
    Description: The ID of the VPC

  ALBSecurityGroupId:
    Type: String
    Description: The ID of the ALB security group

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 security group
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: -1
          SourceSecurityGroupId: !Ref ALBSecurityGroupId
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  EC2SecurityGroupId:
    Description: The ID of the EC2 security group
    Value: !Ref EC2SecurityGroup
