AWSTemplateFormatVersion: "2010-09-09"
Description: VPC Template with the internet gateway and the nat gateway for provide acces to the ec2 for download resources

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: The CIDR block for the VPC

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: my-vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: internet_gateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

Outputs:
  VpcId:
    Description: The ID of the VPC
    Value: !Ref VPC

  InternetGatewayId:
    Description: The ID of the internet gateway
    Value: !Ref InternetGateway

  AttachGateway:
    Value: !Ref AttachGateway
